const regionData = [
    {
        Country: "United States",
        Region: "Alabama",
        Latitude: 32.8067,
        Longitude: -86.7911,
        RandomValue: 1,
    },
    {
        Country: "United States",
        Region: "Alaska",
        Latitude: 61.3707,
        Longitude: -152.4044,
        RandomValue: 0,
    },
    {
        Country: "United States",
        Region: "Arizona",
        Latitude: 34.2735,
        Longitude: -111.6581,
        RandomValue: 2,
    },
    {
        Country: "United States",
        Region: "California",
        Latitude: 36.7783,
        Longitude: -119.4179,
        RandomValue: 1,
    },
    {
        Country: "United States",
        Region: "Colorado",
        Latitude: 39.5501,
        Longitude: -105.7821,
        RandomValue: 0,
    },
    {
        Country: "United States",
        Region: "Florida",
        Latitude: 27.7663,
        Longitude: -81.6868,
        RandomValue: 2,
    },
    {
        Country: "United States",
        Region: "New York",
        Latitude: 40.7128,
        Longitude: -74.006,
        RandomValue: 1,
    },
    {
        Country: "United States",
        Region: "Texas",
        Latitude: 31.9686,
        Longitude: -99.9018,
        RandomValue: 0,
    },
    {
        Country: "United Kingdom",
        Region: "England",
        Latitude: 55.3781,
        Longitude: -3.436,
        RandomValue: 2,
    },
    {
        Country: "United Kingdom",
        Region: "Scotland",
        Latitude: 56.4907,
        Longitude: -4.2026,
        RandomValue: 1,
    },
    {
        Country: "United Kingdom",
        Region: "Wales",
        Latitude: 52.1307,
        Longitude: -3.7837,
        RandomValue: 0,
    },
    {
        Country: "United Kingdom",
        Region: "Northern Ireland",
        Latitude: 54.7877,
        Longitude: -5.7016,
        RandomValue: 2,
    },
    {
        Country: "Canada",
        Region: "Alberta",
        Latitude: 53.9333,
        Longitude: -116.5765,
        RandomValue: 1,
    },
    {
        Country: "Canada",
        Region: "British Columbia",
        Latitude: 53.7267,
        Longitude: -127.6476,
        RandomValue: 0,
    },
    {
        Country: "Canada",
        Region: "Ontario",
        Latitude: 51.2538,
        Longitude: -85.3232,
        RandomValue: 2,
    },
    {
        Country: "Canada",
        Region: "Quebec",
        Latitude: 46.8139,
        Longitude: -71.2082,
        RandomValue: 1,
    },
    {
        Country: "Canada",
        Region: "Nova Scotia",
        Latitude: 44.682,
        Longitude: -63.7443,
        RandomValue: 0,
    },
    {
        Country: "Australia",
        Region: "New South Wales",
        Latitude: -33.8688,
        Longitude: 151.2093,
        RandomValue: 2,
    },
    {
        Country: "Australia",
        Region: "Queensland",
        Latitude: -27.4698,
        Longitude: 153.0251,
        RandomValue: 1,
    },
    {
        Country: "Australia",
        Region: "Victoria",
        Latitude: -37.8136,
        Longitude: 144.9631,
        RandomValue: 0,
    },
    {
        Country: "Australia",
        Region: "Western Australia",
        Latitude: -30.0,
        Longitude: 120.0,
        RandomValue: 2,
    },
    {
        Country: "Australia",
        Region: "South Australia",
        Latitude: -30.0,
        Longitude: 138.5,
        RandomValue: 1,
    },
    {
        Country: "Germany",
        Region: "Bavaria",
        Latitude: 48.7904,
        Longitude: 11.4979,
        RandomValue: 0,
    },
    {
        Country: "Germany",
        Region: "Berlin",
        Latitude: 52.52,
        Longitude: 13.405,
        RandomValue: 2,
    },
    {
        Country: "Germany",
        Region: "Hamburg",
        Latitude: 53.5511,
        Longitude: 9.9937,
        RandomValue: 1,
    },
    {
        Country: "Germany",
        Region: "Hesse",
        Latitude: 50.1109,
        Longitude: 8.6821,
        RandomValue: 0,
    },
    {
        Country: "Germany",
        Region: "North Rhine-Westphalia",
        Latitude: 51.4332,
        Longitude: 7.6619,
        RandomValue: 2,
    },
    {
        Country: "France",
        Region: "Brittany",
        Latitude: 48.3962,
        Longitude: -2.5812,
        RandomValue: 1,
    },
    {
        Country: "France",
        Region: "Grand Est",
        Latitude: 48.695,
        Longitude: 6.3522,
        RandomValue: 0,
    },
    {
        Country: "France",
        Region: "Île-de-France",
        Latitude: 48.8566,
        Longitude: 2.3522,
        RandomValue: 2,
    },
    {
        Country: "France",
        Region: "Normandy",
        Latitude: 49.4144,
        Longitude: 0.8334,
        RandomValue: 1,
    },
    {
        Country: "France",
        Region: "Provence-Alpes-Côte d'Azur",
        Latitude: 43.84,
        Longitude: 6.2444,
        RandomValue: 0,
    },
    {
        Country: "Japan",
        Region: "Hokkaido",
        Latitude: 43.0642,
        Longitude: 141.3469,
        RandomValue: 2,
    },
    {
        Country: "Japan",
        Region: "Tokyo",
        Latitude: 35.6762,
        Longitude: 139.6503,
        RandomValue: 1,
    },
    {
        Country: "Japan",
        Region: "Osaka",
        Latitude: 34.6937,
        Longitude: 135.5023,
        RandomValue: 0,
    },
    {
        Country: "Japan",
        Region: "Kyoto",
        Latitude: 35.0116,
        Longitude: 135.7681,
        RandomValue: 2,
    },
    {
        Country: "Japan",
        Region: "Okinawa",
        Latitude: 26.6059,
        Longitude: 127.9794,
        RandomValue: 1,
    },
    {
        Country: "China",
        Region: "Beijing",
        Latitude: 39.9042,
        Longitude: 116.4074,
        RandomValue: 0,
    },
    {
        Country: "China",
        Region: "Guangdong",
        Latitude: 23.3419,
        Longitude: 113.4244,
        RandomValue: 2,
    },
    {
        Country: "China",
        Region: "Shanghai",
        Latitude: 31.2304,
        Longitude: 121.4737,
        RandomValue: 1,
    },
    {
        Country: "China",
        Region: "Sichuan",
        Latitude: 30.6586,
        Longitude: 104.0648,
        RandomValue: 0,
    },
    {
        Country: "China",
        Region: "Zhejiang",
        Latitude: 29.1858,
        Longitude: 120.1536,
        RandomValue: 2,
    },
    {
        Country: "India",
        Region: "Maharashtra",
        Latitude: 19.7515,
        Longitude: 75.7139,
        RandomValue: 1,
    },
    {
        Country: "India",
        Region: "Uttar Pradesh",
        Latitude: 27.0597,
        Longitude: 80.6302,
        RandomValue: 0,
    },
    {
        Country: "India",
        Region: "Tamil Nadu",
        Latitude: 11.1271,
        Longitude: 78.6569,
        RandomValue: 2,
    },
    {
        Country: "India",
        Region: "Karnataka",
        Latitude: 15.3173,
        Longitude: 75.7139,
        RandomValue: 1,
    },
    {
        Country: "India",
        Region: "Gujarat",
        Latitude: 22.2587,
        Longitude: 71.1924,
        RandomValue: 0,
    },
    {
        Country: "Brazil",
        Region: "São Paulo",
        Latitude: -23.5505,
        Longitude: -46.6333,
        RandomValue: 2,
    },
    {
        Country: "Brazil",
        Region: "Rio de Janeiro",
        Latitude: -22.9068,
        Longitude: -43.1729,
        RandomValue: 1,
    },
    {
        Country: "Brazil",
        Region: "Minas Gerais",
        Latitude: -18.5122,
        Longitude: -44.555,
        RandomValue: 0,
    },
    {
        Country: "Brazil",
        Region: "Bahia",
        Latitude: -12.9714,
        Longitude: -38.5014,
        RandomValue: 2,
    },
    {
        Country: "Brazil",
        Region: "Rio Grande do Sul",
        Latitude: -30.017,
        Longitude: -51.2287,
        RandomValue: 1,
    },
    {
        Country: "Mexico",
        Region: "Mexico City",
        Latitude: 19.4326,
        Longitude: -99.1332,
        RandomValue: 0,
    },
    {
        Country: "Mexico",
        Region: "Jalisco",
        Latitude: 20.6597,
        Longitude: -103.3496,
        RandomValue: 2,
    },
    {
        Country: "Mexico",
        Region: "Nuevo León",
        Latitude: 25.6866,
        Longitude: -100.3161,
        RandomValue: 1,
    },
    {
        Country: "Mexico",
        Region: "Veracruz",
        Latitude: 19.1738,
        Longitude: -96.1467,
        RandomValue: 0,
    },
    {
        Country: "Mexico",
        Region: "Puebla",
        Latitude: 19.0458,
        Longitude: -98.2063,
        RandomValue: 2,
    },
    {
        Country: "Russia",
        Region: "Moscow",
        Latitude: 55.7558,
        Longitude: 37.6173,
        RandomValue: 1,
    },
    {
        Country: "Russia",
        Region: "Saint Petersburg",
        Latitude: 59.9343,
        Longitude: 30.3351,
        RandomValue: 0,
    },
    {
        Country: "Russia",
        Region: "Novosibirsk",
        Latitude: 54.9885,
        Longitude: 82.1026,
        RandomValue: 2,
    },
    {
        Country: "Russia",
        Region: "Yekaterinburg",
        Latitude: 56.8389,
        Longitude: 60.6057,
        RandomValue: 1,
    },
    {
        Country: "Russia",
        Region: "Kazan",
        Latitude: 55.8304,
        Longitude: 49.0661,
        RandomValue: 0,
    },
    {
        Country: "Italy",
        Region: "Lombardy",
        Latitude: 45.4664,
        Longitude: 9.19,
        RandomValue: 2,
    },
    {
        Country: "Italy",
        Region: "Lazio",
        Latitude: 41.9028,
        Longitude: 12.4964,
        RandomValue: 1,
    },
    {
        Country: "Italy",
        Region: "Campania",
        Latitude: 40.8518,
        Longitude: 14.2681,
        RandomValue: 0,
    },
    {
        Country: "Italy",
        Region: "Sicily",
        Latitude: 37.5992,
        Longitude: 14.0159,
        RandomValue: 2,
    },
    {
        Country: "Italy",
        Region: "Veneto",
        Latitude: 45.438,
        Longitude: 12.3275,
        RandomValue: 1,
    },
    {
        Country: "Spain",
        Region: "Andalusia",
        Latitude: 37.3886,
        Longitude: -4.553,
        RandomValue: 0,
    },
    {
        Country: "Spain",
        Region: "Catalonia",
        Latitude: 41.5925,
        Longitude: 1.5209,
        RandomValue: 2,
    },
    {
        Country: "Spain",
        Region: "Madrid",
        Latitude: 40.4168,
        Longitude: -3.7038,
        RandomValue: 1,
    },
    {
        Country: "Spain",
        Region: "Valencia",
        Latitude: 39.4699,
        Longitude: -0.3763,
        RandomValue: 0,
    },
    {
        Country: "Spain",
        Region: "Galicia",
        Latitude: 42.6,
        Longitude: -8.78,
        RandomValue: 2,
    },
    {
        Country: "South Korea",
        Region: "Seoul",
        Latitude: 37.5665,
        Longitude: 126.978,
        RandomValue: 1,
    },
    {
        Country: "South Korea",
        Region: "Busan",
        Latitude: 35.1796,
        Longitude: 129.0756,
        RandomValue: 0,
    },
    {
        Country: "South Korea",
        Region: "Incheon",
        Latitude: 37.4563,
        Longitude: 126.7052,
        RandomValue: 2,
    },
    {
        Country: "South Korea",
        Region: "Daegu",
        Latitude: 35.8714,
        Longitude: 128.6014,
        RandomValue: 1,
    },
    {
        Country: "South Korea",
        Region: "Gwangju",
        Latitude: 35.1595,
        Longitude: 126.8526,
        RandomValue: 0,
    },
    {
        Country: "Netherlands",
        Region: "North Holland",
        Latitude: 52.386,
        Longitude: 4.8897,
        RandomValue: 2,
    },
    {
        Country: "Netherlands",
        Region: "South Holland",
        Latitude: 52.02,
        Longitude: 4.4844,
        RandomValue: 1,
    },
    {
        Country: "Netherlands",
        Region: "Utrecht",
        Latitude: 52.0907,
        Longitude: 5.1214,
        RandomValue: 0,
    },
    {
        Country: "Netherlands",
        Region: "North Brabant",
        Latitude: 51.4828,
        Longitude: 5.4783,
        RandomValue: 2,
    },
    {
        Country: "Netherlands",
        Region: "Gelderland",
        Latitude: 52.0679,
        Longitude: 5.4865,
        RandomValue: 1,
    },
    {
        Country: "Saudi Arabia",
        Region: "Riyadh",
        Latitude: 24.7136,
        Longitude: 46.6753,
        RandomValue: 0,
    },
    {
        Country: "Saudi Arabia",
        Region: "Makkah",
        Latitude: 21.3891,
        Longitude: 39.8579,
        RandomValue: 2,
    },
    {
        Country: "Saudi Arabia",
        Region: "Eastern Province",
        Latitude: 27.262,
        Longitude: 49.8006,
        RandomValue: 1,
    },
    {
        Country: "Saudi Arabia",
        Region: "Madinah",
        Latitude: 24.47,
        Longitude: 39.6122,
        RandomValue: 0,
    },
    {
        Country: "Saudi Arabia",
        Region: "Asir",
        Latitude: 18.2228,
        Longitude: 42.7135,
        RandomValue: 2,
    },
    {
        Country: "South Africa",
        Region: "Gauteng",
        Latitude: -26.2041,
        Longitude: 28.0473,
        RandomValue: 1,
    },
    {
        Country: "South Africa",
        Region: "Western Cape",
        Latitude: -33.9249,
        Longitude: 18.4241,
        RandomValue: 0,
    },
    {
        Country: "South Africa",
        Region: "KwaZulu-Natal",
        Latitude: -29.7682,
        Longitude: 30.3798,
        RandomValue: 2,
    },
    {
        Country: "South Africa",
        Region: "Eastern Cape",
        Latitude: -33.9629,
        Longitude: 26.5603,
        RandomValue: 1,
    },
    {
        Country: "South Africa",
        Region: "Free State",
        Latitude: -29.0852,
        Longitude: 26.2237,
        RandomValue: 0,
    },
    {
        Country: "Turkey",
        Region: "Istanbul",
        Latitude: 41.0082,
        Longitude: 28.9784,
        RandomValue: 2,
    },
    {
        Country: "Turkey",
        Region: "Ankara",
        Latitude: 39.9334,
        Longitude: 32.8597,
        RandomValue: 1,
    },
    {
        Country: "Turkey",
        Region: "Izmir",
        Latitude: 38.4192,
        Longitude: 27.1287,
        RandomValue: 0,
    },
    {
        Country: "Turkey",
        Region: "Antalya",
        Latitude: 36.8841,
        Longitude: 30.7042,
        RandomValue: 2,
    },
    {
        Country: "Turkey",
        Region: "Bursa",
        Latitude: 40.1826,
        Longitude: 29.061,
        RandomValue: 1,
    },
];

export default regionData;
